### ISSUE TITLE
Found some bugs

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#203] opened 2024-03-15 14:52 UTC
Hey @gh0stzk! Your new rices look fantastic. I've been using an old fork of your dotfiles and made some heavy modifications to them, so I've been manually installing them. However, I found some bugs:

1. When pressing mod + h or mod + u twice in z0mbi3 & andrea rice (which have the eww bar), the new HideBar script glitches and fails to render it properly.

2. The bar in z0mbi3 rice doesn't react to hover events

3. In the `set_eww_colors` function (found in Theme.sh of brenda, daniela, marisol), there's a typo in the string; it says "Eww colors for Emilia rice"

4. In the `set_term_config` function (found in Theme.sh of marisol), there's another typo; it says "(Kanagawa) color scheme for Marisol Rice" instead of "(Dracula) color scheme for Marisol Rice".

**Comment by gh0stzk** [comment] 2024-03-15 21:04
Thank you, the first one, i will check in deep. The second point i cant reproduce it, are you running the last eww binary?? in my case it works fine in all hover events.

will fix the typos asap.

**Comment by gh0stzk** [comment] 2024-03-15 22:33
I already push the fix for hidebar and that must fix your first point. Be sure you use latest eww, because the script now uses the flag "active-windows" in eww command.
Typos corrected.
Your second point i cant reproduce it. be sure you use eww 0.5.0
`eww -V`

**Comment by 0xN1nja** [comment] 2024-03-16 09:05
I'm currently using version 0.5.0 of Eww. The HideScript is still not functioning properly for Andrea Rice. Additionally, there seems to be an issue with font rendering in Daniela's setup:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/faec34c6-1210-439e-a5b1-7cf3381072e9)

I also have a question regarding the difference between the old and new configurations in my bspwmrc:

Old configuration:
```bash
workspaces() {
    name=1
    for monitor in $(bspc query -M); do
        bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
        #bspc monitor ${monitor} -n "$name" -d '' '' '' '' '' ''
        ((name++))
    done
}
```

New configuration:
```bash
for monitor in $(xrandr -q | grep -w 'connected' | cut -d' ' -f1); do
    bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
    #bspc monitor "$monitor" -d '' '' '' '' '' ''
done
```

What is the difference between them?

**Comment by gh0stzk** [comment] 2024-03-16 15:00
For the bar in Daniela, did you copy the new Bebasneue.ttf and drop in your fonts dir??

The difference in that code is, use the xrander to get monitors name and the monitor is not added automatically, https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup .
But perfectly you can leave as the old code and will work too. the change is to let people configure theis monitors.

I tested the andrea bar, and apparently it is a problem with eww, which cannot close or start the daemon if you press the keys continuously and too fast.

**Comment by 0xN1nja** [comment] 2024-03-16 16:07
After I copied Bebasneue.ttf to `~/.local`, the bar was fixed. Thanks!

Lastly, in Brenda rice, the `weather` component isn't properly padded (when mpd isn't playing anything):
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/bdc4b752-3a81-4388-b24f-4c3c97ca4007)

But it gets padded when you play something with mpd:
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/fb9b605d-5566-451a-8997-9ba8f6e887bd)

**Comment by gh0stzk** [comment] 2024-03-16 20:20
Ready, i push the fixes.

**Comment by gh0stzk** [comment] 2024-03-16 20:23
Will close this issue now, if you found something else, create a new issue pls.

**Closed by gh0stzk** 2024-03-16 20:23 UTC

**Comment by 0xN1nja** [comment] 2024-03-17 12:42
The `weather` component now receives additional padding when a song is being played:
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/aa964191-7b41-439c-90d2-513582c7fea3)

**Comment by 0xN1nja** [comment] 2024-03-17 16:58
Another bug: System tray is not rendering properly in Melissa rice (maybe related to polybar)
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/9abcadaf-c4da-4a9e-bdbb-3383c82bf64d)

**Comment by 0xN1nja** [comment] 2024-03-19 07:16
@gh0stzk sorry for the ping

**Comment by gh0stzk** [comment] 2024-03-19 17:56
No problem i already fix the weather module, the discord icon, in systray i dont know, it only happend with discord or what app it is??? In my case nothing wrong.

![Shot-2024-03-19-115101](https://github.com/gh0stzk/dotfiles/assets/67278339/78418d6e-916d-4a31-8b5a-b235e270cbc8)

I just got new laptop and i fixing/editing/Optmizing the battery and brightness modules in all rices, i will push the weather fix when i finish updating all the other things.
