### ISSUE TITLE
brightness control

### ISSUE THREAD

**Issue by skiss0** [gh0stzk/dotfiles#142] opened 2023-11-03 21:55 UTC
Are the brightness control commands missing in the   
sxhkdrc file or am I wrong?

it doesn't work  if i ad a coomand like:
XF86MonBrightness{Up,Down}
            brightnesssctl s 10{+,-}

I need to change something in the Brightness script?

**Comment by gh0stzk** [comment] 2023-11-03 22:56
I am realizing thanks to your comment that I deleted that part of the configuration by mistake in an update. I already fixed it and in a moment I will add the commit. Meanwhile I leave you what needs to be added to the sxhkdrc file

```bash
# Manage brightness
XF86MonBrightness{Up,Down}
    sh Brightness {up,down}
```

**Comment by skiss0** [comment] 2023-11-03 23:07
Thanks so much for the reply, unfortunately this command doesn't work either

**Comment by gh0stzk** [comment] 2023-11-03 23:20
dis you refresh the sxhkd daemon after edit the config?? `super + esc` to reload the daemon.

**Comment by skiss0** [comment] 2023-11-03 23:29
I restarted bspwm with super + alt + r, I also restarted the daemon, I also tried without 'sh', but it doesn't work, maybe there's something wrong with the Brightness script?!

**Comment by gh0stzk** [comment] 2023-11-04 03:33
Ok first we have to check that the brightnessctl app is installed and it works.

Open a terminal and type:

`which brightnessctl`

Is installed? then write this commands:

`brightnessctl set +5%`

`brightnessctl set 10%-`

That commands works?

If they work then we need to verify that the script works correctly, type in the terminal:

`Brightness up`

`Brightness down`

If all the above works correctly then the problem is in sxhkd.

But if nothing works Then the problem is the brightnessctl app.
I chose that app because it is the one that works best on most computers with Intel or AMD.

There are other applications that, in your case, if brightnessctl does not work, others may work. For example xbacklight `sudo pacman -S xorg-xbacklight`

**Comment by skiss0** [comment] 2023-11-04 04:17
thanks, it works correctly from the terminal with both brightnessctl and Brightness up, and the notification can be seen very well on the bar and in the top right corner.
I had read that someone had the same problem and that the Brightness module was not active on the file, could it be that?  I also noticed that some people use xbacklight, but is it just a matter of modifying sxhkd?

**Comment by gh0stzk** [comment] 2023-11-04 19:03
It's surely something related to sxhkd then.
What login manager do you use? if you use lightdm, that login manager creates a file called .xsession-errors in your home directory, if you have that file, press the corresponding keys several times to increase or decrease the brightness, then immediately open that file and look at the logs for a clue as to what may be happening.

If you don't have that file, open a terminal, type killall sxhkd and then reload the daemon but right there in the terminal with sxhkd -c "$HOME"/.config/bspwm/sxhkdrc

That will keep the process in the terminal and the errors will be visible. Press the corresponding keys to change the brightness and see what the terminal displays.

Then just restart bspwm to continue as usual.

**Comment by skiss0** [comment] 2023-11-04 19:25
🤦 I had two sxhkdrc 1 from an old installation in .config/bspwm/sxhkdrc and one in /dotfiles/config/bspwm/sxhkdrc I copied the command and it works I'm sorry it's my fault 🫣

**Comment by gh0stzk** [comment] 2023-11-05 00:09
Ok then, i will close the issue.

**Closed by gh0stzk** 2023-11-05 00:09 UTC
